### ISSUE TITLE
readStringUntil does not include termination char

### ISSUE THREAD

**Issue by vincadrn** [burjoy/skripsing#7]
## Description
There is actually `\r\n` (CR+LF) between each rows of the log file, but since `readStringUntil` does not include the termination char `\n` ([line ref](https://github.com/burjoy/skripsing/blob/17b66e550394a98db0cfe3d57e17bb16a396f02f/send%20bluetooth/send_bluetooth_to_adrian.ino#L161C32-L161C44)), only the `\r` part is included, resulting in partial output in the stream.

[This](https://www.baeldung.com/linux/vim-m-character-meaning) explains the `^M` shown when debugging.

## Expected sample
`2020-11-12T13:14:15\t1010\r\n`

## Actual sample:
`2020-11-12T13:14:15\t1010\r`

**Comment by burjoy** [comment]
solved, caranya agak cheesy sebetulnya, string hasil_baca_file gw tambahin \n setiap string replacenya udah selesai
![image](https://github.com/burjoy/skripsing/assets/51292479/bd582bb5-dad8-44a3-b213-f5bff5b25259)
